version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - orders-api
      - payments-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  
  orders-redis:
    image: redis:latest
    ports:
      - "6378:6378"
    command: ["redis-server", "--port", "6378"]
  orders-api:
    build:
      context: ./orders
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
    environment:
      - REDIS_ADDR=orders-redis:6378
      - MQ_ADDR=amqp://user:password@rabbitmq:5672
      - SERVER_PORT=8888
    depends_on:
      - orders-redis
  
  payments-redis:
    image: redis:latest
    ports:
      - "6379:6379"
  payments-api:
    build:
      context: ./payments
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=payments-redis:6379
      - MQ_ADDR=amqp://user:password@rabbitmq:5672
      - SERVER_PORT=8080
    depends_on:
      - payments-redis