services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - orders-api
      - payments-api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  proto:
    build:
      context: ./proto
      dockerfile: Dockerfile
    volumes:
      - .:/workspace

  orders-redis:
    image: redis:latest
    command: ["redis-server", "--port", "6378"]
  orders-api:
    build:
      context: .
      dockerfile: orders/Dockerfile
    environment:
      - REDIS_ADDR=orders-redis:6378
      - MQ_ADDR=amqp://user:password@rabbitmq:5672
      # - MQ_ADDR=amqp://user:password@rabbitmqq:5672
      - SERVER_PORT=8888
    depends_on:
      - orders-redis
      - proto
      - rabbitmq

  payments-redis:
    image: redis:latest
  payments-api:
    build:
      context: .
      dockerfile: payments/Dockerfile
    environment:
      - REDIS_ADDR=payments-redis:6379
      - MQ_ADDR=amqp://user:password@rabbitmq:5672
      - SERVER_PORT=8080
    depends_on:
      - payments-redis
      - proto
      - rabbitmq
