version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  orders-redis:
    image: redis:latest
    ports:
      - "6378:6378"
    command: ["redis-server", "--port", "6378"]
  payments-redis:
    image: redis:latest
    ports:
      - "6379:6379"
  payments-api:
    build:
      context: ./payments
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=payments-redis:6379
      - SERVER_PORT=8080
    depends_on:
      - payments-redis